{"name": "При создании пользователя с логином, который уже есть, возвращается ошибка", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\n  \n  - Этот логин уже используется\n  + Этот логин уже используется. Попробуйте другой.", "trace": "self = <tests.test_create_courier.TestCourierEndpoints object at 0x000001CDF1462360>\n\n    @allure.title('При создании пользователя с логином, который уже есть, возвращается ошибка')\n    def test_registration_twice_false_text(self):\n        a = TestDataHelper.create_registration_body()\n        first_registration_request = ScooterApi.registration(a)\n        assert first_registration_request.status_code == 201\n        second_registration_request = ScooterApi.registration(a)\n>       assert second_registration_request.json()[\"message\"] == \"Этот логин уже используется\"\nE       AssertionError: assert 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\nE         \nE         - Этот логин уже используется\nE         + Этот логин уже используется. Попробуйте другой.\n\ntests\\test_create_courier.py:64: AssertionError"}, "start": 1725227661925, "stop": 1725227664185, "uuid": "ffcfe074-0298-43ff-9506-38d3b78fd25c", "historyId": "1c92b041cd9706a264c5fcfacb393ce0", "testCaseId": "1c92b041cd9706a264c5fcfacb393ce0", "fullName": "tests.test_create_courier.TestCourierEndpoints#test_registration_twice_false_text", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCourierEndpoints"}, {"name": "host", "value": "Notebook"}, {"name": "thread", "value": "9016-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}